apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
#- name: ghcr.io/wlgns5376/example-app
#  newTag: latest
- name: shclub/edu4
  newTag: v2
namePrefix: dev-
#commonLabels:
#  variants: development
patchesStrategicMerge:
- replica_count.yaml
- cpu_count.yaml
resources:
- ../../base
